precision: 16-mixed
max_epochs: 75
max_steps: 1000
num_nodes: 1
devices: -1
sync_batchnorm: True
default_root_dir: ${exp_dir}
num_sanity_val_steps: 0
accumulate_grad_batches: 1
log_every_n_steps: 50
gradient_clip_val: 5.0
use_distributed_sampler: False

