python vlr/train.py exp_dir=/home/duytran/Desktop/vlr/outputs \
                exp_name=vlr_temp\
                streaming=True \
                data.modality=video \
                data.batch_size=7 \
                data.num_workers=16 \
                data.max_frames=750 \
                data.max_frames_val=500 \
                data.shuffle=True \
                data.select=100 \
                data.dataset.root_dir=/home/duytran/Downloads/vlr\
                data.dataset.train_dir=cropping \
                data.dataset.test_size=0.01 \
                ckpt_path=\
                pretrained_model_path=\
                transfer_frontend=False\
                transfer_encoder=False\
                optimizer.lr=1e-4 \
                optimizer.weight_decay=1e-5 \
                optimizer.warmup_epochs=2 \
                optimizer.scheduler=step \
                optimizer.name=adamw \
                trainer.max_epochs=10 \
                trainer.precision=32 \
                trainer.max_steps=100000000 \
                trainer.accumulate_grad_batches=1 \
                trainer.log_every_n_steps=10 \
                trainer.gradient_clip_val=5.0 