python vlr/train.py exp_dir=/home/duytran/Desktop/vlr/outputs \
                exp_name="1st_v2.1_200h_visual_prerained"\
                streaming=True \
                data.modality=video \
                data.batch_size=7 \
                data.num_workers=16 \
                data.max_frames=750 \
                data.max_frames_val=500 \
                data.shuffle=True \
                data.select=-1 \
                data.dataset.root_dir=/media/duytran/TRANSCEND/vlrs/data/v2.1\
                data.dataset.train_dir=stage_4 \
                data.dataset.test_size=0.01 \
                ckpt_path=\
                pretrained_model_path=/home/duytran/Desktop/vlr/pretrain_model/vsr_trlrs3vox2_base.pth\
                transfer_frontend=False\
                transfer_encoder=True\
                optimizer.lr=1e-4 \
                optimizer.weight_decay=1e-5 \
                optimizer.warmup_epochs=0 \
                optimizer.scheduler=poly \
                optimizer.name=adamw \
                trainer.max_epochs=10 \
                trainer.precision=32 \
                trainer.max_steps=100000000 \
                trainer.accumulate_grad_batches=1 \
                trainer.log_every_n_steps=1000 \
                trainer.gradient_clip_val=5.0 